name: kembangringgit_app
description: Aplikasi Manajemen Desa Kembang Ringgit
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  get: ^4.6.5
  ionicons: ^0.2.1
  http: ^0.13.3
  firebase_core: ^2.10.0
  firebase_core_web: ^2.10.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.0
  firebase_database: ^10.0.7
  firebase_storage: any
  shared_preferences: ^2.0.11
  file_picker: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo_app_blue.png
    - assets/logo_app_white.png
    - assets/logo_weather.png
    - assets/icon_document.png
    - assets/icon_report.png
    - assets/icon_calendar.png
    - assets/profile_alpan.jpg
    - assets/profile_arya.jpeg

